### ISSUE TITLE
operators for select error redmine 2.2.0

### ISSUE THREAD

**Issue by brianveltman** [dkuk/redmine_extra_query_operators#2]
Still having a Template error: operators_for_select on redmine 2.2.0.

Connecting to database specified by database.yml
Starting Charts Plugin for RedMine
OpenIdAuthentication.store is nil. Using in-memory store.
Started GET "/projects/bmg/issues" for 80.60.215.244 at Sun Jan 06 19:37:46 +0100 2013
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"bmg"}
  Current user: Brian (id=3)
  Rendered plugins/redmine_extra_query_operators/app/views/queries/_filters.html.erb (112.1ms)
  Rendered issues/index.html.erb (121.7ms)
  Rendered plugins/redmine_anonymous_authors/app/views/issues/index.html.erb (124.8ms)
  Rendered plugins/redmine_anonymous_watchers/app/views/issues/index.html.erb within layouts/base (129.3ms)
Completed 500 Internal Server Error in 565ms

ActionView::Template::Error (undefined method `operators_for_select' for #<#<Class:0xf36d3dd4>:0xf36d13a4>):
    43:     </td>
    44:     <td class="operator">
    45:         <%= label_tag "operators_#{field}", l(:description_filter), :class => "hidden-for-sighted" %>
    46:         <%= select_tag "op[#{field}]", options_for_select(operators_for_select(options[:type]),
    47:                         query.operator_for(field)), :id => "operators_#{field}",
    48:                         :onchange => "toggle_operator('#{field}');" %>
    49:     </td>
  app/views/issues/index.html.erb:18:in`_app_views_issues_index_html_erb___440755701__105571418'
  app/views/issues/index.html.erb:11:in `_app_views_issues_index_html_erb___440755701__105571418'
  app/controllers/issues_controller.rb:83:in`index'
  app/controllers/issues_controller.rb:82:in `index'

**Comment by dkuk** [comment]
We don't tested on 2.2.0 but we plan to migrate to lates RM till Jan ends. It could fails of course. There are a lot of changes in filters of 2.2.0 due group sorting was introduced.

**Comment by markedagain** [comment]
@dkuk i noticed this plugin working great on rmplus demo site, ( im presuming this is you ) any way of updating this plugin so it works with latest redmine ?

**Comment by dkuk** [comment]
Sorry, I'am not shure if plugin works nice.
It does not falls, but other...at least jquery datetime picker does not provides letters in date field, so relative dates can't be submitted.
I'll try to look throught the code, but have not enought time to fix it. We not strongly needed in this plugin now. It's usefult but...truly say - it is no any work on this plugin now.
You can find common activity on it here:    http://www.redmine.org/plugins/redmine_extra_query_operators
